### ISSUE TITLE
stubs/libcuda.so is loaded instead of libcuda.so

### ISSUE THREAD

**Issue by tscmoo** [pytorch/tensorpipe#294]
On my machine, tensorpipe loads `/usr/lib/x86_64-linux-gnu/stubs/libcuda.so` instead of `/usr/lib/x86_64-linux-gnu/libcuda.so`. The stubs libcuda.so is just a stub and does not have any (correct) function implementations, resulting in the exception `In create at /home/a/nethack/moorpc/src/tensorpipe/tensorpipe/common/cuda_lib.h:105 "res != CUDA_SUCCESS"`

Changing tensorpipe from loading "libcuda.so" to "libcuda.so.1" fixes/works around the issue.

The same issue occurs on my devfair, where it loads `/public/apps/cuda/10.1/lib64/stubs/libcuda.so`. (pytorch has already loaded `/lib/x86_64-linux-gnu/libcuda.so.1`)

**Comment by lw** [comment]
Funny, we've got a similar report recently, so I guess this is really a thing. Do you know why the stub is picked up instead of the other library? Could you let me know the output of `/sbin/ldconfig -p | grep libcuda.so` and the value of `LD_LIBRARY_PATH`? I also wonder whether this could be due to some CMake misconfiguration, which perhaps ends up setting an RPATH on TensorPipe's shared library?

I think we can apply the fix you suggested and use `libcuda.so.1`, but I'd also like to understand the root cause of this. Thanks!

**Comment by tscmoo** [comment]
```
$ /sbin/ldconfig -p | grep libcuda.so
        libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
        libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so
```

```RUNPATH=/home/a/anaconda3/envs/hackrl/lib/python3.7/site-packages/torch/lib:/home/a/anaconda3/envs/pytorch/lib:/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs```
seems to be the culprit - the only folder here with a libcuda.so is the last one, stubs.

So the issue is probably that my application links to pytorch, which in turn links to cuda, resulting in that RPATH.

**Comment by tscmoo** [comment]
I tested removing the stubs path with chrpath, and that fixed the issue and let tensorpipe load the correct libcuda.so.

**Comment by lw** [comment]
Thanks for checking this and letting us know! I now wonder where that RPATH comes from and if it's set on purpose. If you're building PyTorch from source, and if it's not too much of a hassle, could you try to remove the stubs entries from this line and try rebuilding again?

https://github.com/pytorch/pytorch/blob/fd41ed1ccef68e88e075c7b633409644c22f0782/cmake/public/cuda.cmake#L187

**Comment by lw** [comment]
Another thing you could try (in addition or alternatively to the above) is to set this option to false when building PyTorch: https://github.com/pytorch/pytorch/blob/bc856b49d4ef0cc16ef30ad866f5d59d5d12267c/cmake/Dependencies.cmake#L16 (it may very well cause build failures, but it may be worth a try...)

**Comment by tscmoo** [comment]
I'm not building pytorch from scratch, so that would be too much hassle for me to test right now, sorry!

**Comment by lw** [comment]
Ok, no worries! I'll try to check with the PyTorch team if they consider this a bug and whether there's something they can do about it...

**Comment by beauby** [comment]
Fixed by #296.

**Comment by Jiangjiangzhang6** [comment]
> /sbin/ldconfig -p | grep libcuda.so

If the system  didnot contain the file, whould  make ln -l from my conda enviroment?

**Comment by lw** [comment]
We're talking about the CUDA driver, you should check with your system administrator why it isn't installed
